version: '3'

tasks:
  build-sse:
    desc: Generate Senior Software Engineer CV (PDF to pdf/)
    cmds:
      - uv run rendercv render src/Anton_Vusatyi_CV_Senior_Software_Engineer.yaml --pdf-path ../pdf/Anton_Vusatyi_CV_Senior_Software_Engineer.pdf -nomd -nohtml -nopng

  build-lse:
    desc: Generate Lead Software Engineer CV (PDF to pdf/)
    cmds:
      - uv run rendercv render src/Anton_Vusatyi_CV_Lead_Software_Engineer.yaml --pdf-path ../pdf/Anton_Vusatyi_CV_Lead_Software_Engineer.pdf -nomd -nohtml -nopng

  build-fse:
    desc: Generate Fullstack Software Engineer CV (PDF to pdf/)
    cmds:
      - uv run rendercv render src/Anton_Vusatyi_CV_Fullstack_Software_Engineer.yaml --pdf-path ../pdf/Anton_Vusatyi_CV_Fullstack_Software_Engineer.pdf -nomd -nohtml -nopng
